language: python
python:
    - "3.6"
install:
    - pip install tox flake8 
script:
    - flake8 src tests
    - tox

before_deploy: "pip install wheel --upgrade"
deploy:
    provider: pypi
    user: "jelford"
    password: ${PYPI_PASSWORD}
    distributions: "sdist bdist_wheel"
    on:
        tags: true
        branch: master

