name: Build
on: [push]
jobs:
  test:
    runs-on: "ubuntu-latest"
    strategy:
      matrix:
        python-version: ['3.6']
    name: Python ${{ matrix.python-version }} build
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - uses: Gr1N/setup-poetry@v4
    - run: poetry install
    - run: poetry run black --check
    - run: poetry run mypy src
    - run: poetry run pytest
  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
    - run: poetry build
